//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Graber_DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERS()
        {
            this.ORDERS_DETAIL = new HashSet<ORDERS_DETAIL>();
        }
    
        public int order_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<double> total_order { get; set; }
        public string state { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS_DETAIL> ORDERS_DETAIL { get; set; }
    }
}
